Models/ErrorViewModel.cs
namespace dt191g_moment2_MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/GamesModel.cs
using System.Collections;
using System.ComponentModel.DataAnnotations;

namespace dt191g_moment2_MVC.Models;

public class GamesModel
{
    [Display(Name = "ID (Ej redigerbar)")]
    public int? id { get; set; }
    
    [Display(Name = "Titel")]
    [Required(ErrorMessage = "Ange en titel")]
    public string? title { get; set; }
    
    [Display(Name = "Genre")]
    [Required(ErrorMessage = "Ange en genre")]
    public string? type { get; set; }
    
    [Display(Name = "Pris")]
    [Required(ErrorMessage = "Ange ett pris")]
    [Range(1, 9999)] // Gräns på pris
    public int? price { get; set; }

    [Display(Name = "Barnvänligt?")]
    public bool kidFriendly { get; set; }
}

Controllers/StartController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using dt191g_moment2_MVC.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

namespace dt191g_moment2_MVC.Controllers;

public class StartController : Controller
{
    private readonly ILogger<StartController> _logger;

    public StartController(ILogger<StartController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        DateTime dateObj = DateTime.Now;
        string dateToday = dateObj.ToString("yyyy-MM-dd");

        // Spara cookie i en dag
        HttpContext.Response.Cookies.Append("date", dateToday, new CookieOptions { 
                Expires = DateTime.Now.AddDays(1)});

        ViewData["date"] = dateToday;
        
        return View();
    }

    [HttpGet("Spel")]
    public IActionResult Games()
    {
        // Hämta data från json-fil och skapa objekt
        var jsonData = System.IO.File.ReadAllText("wwwroot/allGames.json");
        var jsonObj = JsonConvert.DeserializeObject<IEnumerable<GamesModel>>(jsonData);
        ViewBag.games = jsonObj;

        // Hämta cookie
        var cookie = HttpContext.Request.Cookies["date"];
        ViewData["date"] = cookie;
        return View();
    }
    
    [HttpPost("Spel")]
    public IActionResult Games(GamesModel model)
    {
        // Hämta data från json-fil och skapa objekt
        var jsonData = System.IO.File.ReadAllText("wwwroot/allGames.json");
        var jsonObj = JsonConvert.DeserializeObject<IEnumerable<GamesModel>>(jsonData);
        ViewBag.games = jsonObj;
        
        if (ModelState.IsValid)
        {
            // Lagra
            var jsonObjList = JsonConvert.DeserializeObject<List<GamesModel>>(jsonData);

            if (jsonObjList != null)
            {
                jsonObjList.Add(model);
            }
            
            System.IO.File.WriteAllText("wwwroot/allGames.json",
                JsonConvert.SerializeObject(jsonObjList, Formatting.Indented));
            
            ModelState.Clear();
            // Ladda om sidan för att uppdatera listan med spel för användaren
            return RedirectToAction("Games");
        }
        else
        {
            // Ladda inte om sidan för att visa felmeddelanden
            return View();
        }
    }

    [HttpGet("Speltips")]
    public IActionResult GameTip()
    {
        // Hämta data från json-fil och skapa objekt
        var jsonData = System.IO.File.ReadAllText("wwwroot/allGames.json");
        var jsonObj = JsonConvert.DeserializeObject<List<GamesModel>>(jsonData);

        // Hämta cookie (datum)
        var cookie = HttpContext.Request.Cookies["date"];
        ViewData["date"] = cookie;
        return View(jsonObj);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/main.css"/>
</head>
<body>
<div class="container">
    <div class="flex header-main-container">
        <header>
            <h1>SPELDAGS</h1>
            <div id="logo"><i class="fas fa-gamepad"></i></div>
            @* Navbar *@
            @Html.Partial("_Navbar")
        </header>

        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div>
            &copy; 2022 - Amanda Hwatz Björkholm
        </div>
    </footer>
</div>

<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://kit.fontawesome.com/be0f6fe16e.js" crossorigin="anonymous"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Mascot.cshtml
<div class="mascot">
    <div>
        <img src="thank-you-200px.png" alt="Animal Crossing character"/>
    </div>
</div>

Views/Shared/_Navbar.cshtml
<nav>
    <ul class="flex">
        <li>
            <a asp-area="" asp-controller="Start" asp-action="Index">hem</a>
        </li>
        <li id="border-nav">
            <a asp-area="" asp-controller="Start" asp-action="Games">spel</a>
        </li>
        <li>
            <a asp-area="" asp-controller="Start" asp-action="GameTip">speltips</a>
        </li>
    </ul>
</nav>

Views/Start/GameTip.cshtml
@model List<dt191g_moment2_MVC.Models.GamesModel>;

@{
    ViewData["Title"] = "Speltips";
    int index = 0;
        
    if (Model != null)
    {
        // Hämta slumpat spel från listan
        index = new Random().Next(Model.Count());
    }
    var game = Model[index];
    
    // Kontrollera om barnvänligt eller ej
    string kid = "Nej";
    if (game.kidFriendly)
    {
        kid = "Ja";
    }
}

@* Hämta datum *@
<div class="date">
    <div><b>Dagens datum: @ViewData["date"]</b></div>
</div>

<h2>Speltips</h2>
<div class="info">
    <h3>Spela @game.title</h3>
    <p>@game.title är ett roligt spel i genren @game.type. Det kostar endast @game.price kr dessutom. 
        Du hittar övrig information om spelet nedan. Ha så kul!</p>
</div>

@* Skriv ut spelet *@
<div class="flex game-tip-container">
    <div class="game-info">
        <h4>Spelinfo</h4>
        <div>
            <p><b>Titel: </b> @game.title</p>
            <p><b>Genre: </b>@game.type</p>
            <p><b>Pris: </b>@game.price kr</p>
            <p><b>Barnvänligt: @kid</b></p>
        </div>
    </div>

    @Html.Partial("_Mascot")
</div>

Views/Start/Games.cshtml
@using Microsoft.AspNetCore.SignalR.Protocol
@model dt191g_moment2_MVC.Models.GamesModel

@{
    ViewData["Title"] = "Spel";
}

@* Hämta datum *@
<div class="date">
    <div><b>Dagens datum: @ViewData["date"]</b></div>
</div>

<h2>Alla spel</h2>
<div class="flex games-container">
    @* Lista med spel *@
    <div class="games">
        @if (ViewBag.games != null)
        {
            @foreach (var item in ViewBag.games)
            {
                string kid = "Nej";
                if (item.kidFriendly)
                {
                    kid = "Ja";
                }
                <div class="game">
                    <h4>@item?.title</h4>
                    <div class="game-text">
                        <p><b>Genre: </b>@item?.type</p>
                        <p><b>Pris: </b>@item?.price</p>
                        <p><b>Barnvänligt: </b>@kid</p>
                    </div>
                </div>
            }
        }
    </div>

    @* Formulär med lägg till spel *@
    <div class="add-form">
        @{
            // Generera ett ID som är +1 från det sista IDt
            var newId = 1;
            if (ViewBag.games != null)
            {
                var index = ViewBag.games.Count - 1;
                var lastId = ViewBag.games[index];
                newId = lastId.id + 1;
            }
        }
        <h3>Lägg till spel</h3>
        <form method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <label asp-for="id"></label>
            <input type="number" asp-for="id" value="@newId" readonly/>

            <label asp-for="title"></label>
            <input type="text" asp-for="title"/>
            <span asp-validation-for="title"></span>
            
            <label asp-for="type"></label>
            <select asp-for="type">
                <option value="RPG">RPG</option>
                <option value="Äventyr">Äventyr</option>
                <option value="Fantasy">Fantasy</option>
                <option value="Plattform">Plattform</option>
                <option value="Online">Online</option>
                <option value="Relation">Relation</option>
                <option value="FPS">FPS</option>
            </select>
            <span asp-validation-for="type"></span>

            <label asp-for="price"></label>
            <input type="number" asp-for="price"/>
            <span asp-validation-for="price"></span>
            
            <div class="flex kid-field">
                <label asp-for="kidFriendly"></label>
                <input asp-for="kidFriendly" type="checkbox"/>
            </div>
            
            <input type="submit" value="Lägg till" class="btn"/>
        </form>
        
        @Html.Partial("_Mascot")
    </div>
</div>

Views/Start/Index.cshtml
@{
    ViewData["Title"] = "Startsida";
}

@* Hämta datum *@
<div class="date">
    <p><b>Dagens datum: @ViewData["date"]</b></p>
</div>

@* Välkomsttext *@
<h2>Välkommen</h2>
<article class="info">
    <h3>Speltips för alla</h3>
    <p>Du har hittat in på en sida för den som älskar spel och är ute efter goa speltips. Du kanske till och med
        lägger in ditt favoritspel som tips för andra personer som är redo för nästa utmaning. Om så är fallet 
        är du välkommen att glida in på fliken <a asp-area="" asp-controller="Start" asp-action="Games">Spel</a> 
        för att läsa andras speltips och även lägga in ditt eget speltis.</p>
    
    <p>För den som vill leva lite farligt går det att klicka på fliken 
        <a asp-area="" asp-controller="Start" asp-action="GameTip">Speltips</a> då får du ett slumpat speltips!
        Som en sorts spelroulette för den som inte kan bestämma sig.</p>
    
    <p>Nu vill jag bara fylla ut med lite text så det inte ser så tom ut på startsidan. Jag skulle kunna fylla 
        ut med lite genrerad text bara, men jag tror det ser lite mer på riktigt ut om jag faktiskt skriver någonting.
        Du som läser kan få en väderrapport från Norrtälje, det har varit väldigt isigt några dagar och idag snöar det, 
        det kommer bli en intressant lunchpromenad sen.</p>
</article>